# Homework 2 Part 2

Name: Aida
<br>
Surname: Martirosyan

In [1]:
import numpy as np

**Problem 1**

Create a numpy array of dimensions (5,5) with random numbers in range \[0, 1) and print its shape, number of dimensions and data type of its elements.

In [2]:
a = np.random.rand(5,5)
a

array([[0.93610836, 0.67282134, 0.32992624, 0.36606782, 0.27044522],
       [0.01209689, 0.2249099 , 0.10287276, 0.15694297, 0.04924222],
       [0.13416987, 0.6603679 , 0.1256347 , 0.88370192, 0.95268117],
       [0.70799196, 0.35018104, 0.54364751, 0.91040984, 0.69069897],
       [0.03408122, 0.57948259, 0.55927392, 0.01315142, 0.69826483]])

In [3]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(5, 5)
2
float64


**Problem 2**

Change the data type of elements of the numpy array created in Problem 1 to int and keep only even numbers in the array (the shape of output does not matter).

In [4]:
a1 = a.astype(int)
a1.dtype

dtype('int32')

In [6]:
a1[a1 % 2 == 0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

**Problem 3**

Create a numpy array of zeros, a numpy arrays of ones, and an identity matrix of shape (7,7) (all 3). Sum the arrays and print the result.

In [17]:
array0 = np.zeros((7,7))
array0

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [18]:
array1 = np.ones((7,7))
array1

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [21]:
mat = np.eye(7)
mat

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [25]:
sum_ = array0 + array1 + mat
sum_

array([[2., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1., 1., 1.],
       [1., 1., 2., 1., 1., 1., 1.],
       [1., 1., 1., 2., 1., 1., 1.],
       [1., 1., 1., 1., 2., 1., 1.],
       [1., 1., 1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 1., 1., 2.]])

**Problem 4**

Create 10x10 multiplication table as a numpy array.

In [ ]:
# Here is the output
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]

In [43]:
np.c_[1:11:1, 2:21:2, 3:31:3, 4:41:4, 5:51:5, 6:61:6, 7:71:7, 8:81:8, 9:91:9, 10:101:10] # first solution

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [34]:
ls = []   # second solution
for i in range(1, 11):
    for j in range(1, 11):
        ls.append(i*j)
ls = np.array(ls)

In [35]:
ls.reshape(10,10, order = "C")

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

**Problem 5**

Use np.r_ function to generate an array of all single digit precision floating numbers between [0,1] .
The numbers are 0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, and 1. .

In [36]:
np.r_[0:1.1:0.1]

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

**Problem 6**

Use np.c_ function to generate a numpy array where the first column contains even integers between [1,10] and the second columns contain the odd numbers in the same range.

In [40]:
np.c_[2:11:2, 1:10:2]

array([[ 2,  1],
       [ 4,  3],
       [ 6,  5],
       [ 8,  7],
       [10,  9]])

**Problem 7**

Generate a 10000x10000 dimensional matrix with numpy zeroes, resizing numpy array with one element equal to 0, tiling list [0], array+list operations with list [0], and array+list_comprehension approaches, and calculate the execution time.

In [19]:
%%timeit
m = np.zeros((10000, 10000))

10.1 ms ± 808 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
%%timeit
arr = np.array([0])
arr.resize((10000, 10000))

171 ms ± 1.54 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [23]:
%%timeit
np.tile([0], (10000, 10000))

488 ms ± 27 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%%timeit
np.array([[0]*10000]*10000)

In [ ]:
%%timeit
np.array([[0 for i in range(10000)] for i in range(10000)])

**Problem 8**

Generate an one-dimensional array of integers between [0,31337] and compute the mean, variance, max, and min of that array. Perform the same operations using built-in Python operations and list comprehension. Calculate the execution time in both cases.

In [6]:
n = np.r_[0:31338]
n

array([    0,     1,     2, ..., 31335, 31336, 31337])

In [7]:
print(np.mean(n))
print(np.var(n))
print(np.max(n))
print(np.min(n))

15668.5
81839186.91666667
31337
0


In [8]:
s = sum(n)
l = len(n)
mean = s/l
deviations = [(i - mean)**2 for i in n]
variance = sum(deviations)/l

print(mean)
print(variance)
print(max(n))
print(min(n))

15668.5
81839186.91666667
31337
0


In [80]:
%%timeit
np.mean(n)
np.var(n)
np.max(n)
np.min(n)

228 µs ± 3.12 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [81]:
%%timeit
s = sum(n)
l = len(n)
mean = s/l
deviations = [(i - mean)**2 for i in n]
variance = sum(deviations)/l

max(n)
min(n)

102 ms ± 565 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


**Problem 9**

Generate a diagonal matrix with shape (5,5) containing elements in range [1,5] and rotate the matrix by 180 degrees using slicing. The output will be:

[[5, 0, 0, 0, 0],

[0, 4, 0, 0, 0],

[0, 0, 3, 0, 0],

[0, 0, 0, 2, 0],

[0, 0, 0, 0, 1]]

In [37]:
d = np.diag([1,2,3,4,5])
d

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [40]:
d[::-1,::-1]

array([[5, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 1]])

**Problem 10**

Generate 4 matrices of random integers in range \[10,20) with shape(3,3). Use hstack and vstack functions to obtain a 6 by 6 matrix from those 4 matrices. Do the same with np.concatenate function.

In [48]:
mat1 = np.random.randint(low = 10, high = 20, size = (3,3))
mat2 = np.random.randint(low = 10, high = 20, size = (3,3))
mat3 = np.random.randint(low = 10, high = 20, size = (3,3))
mat4 = np.random.randint(low = 10, high = 20, size = (3,3))

In [69]:
print(mat1, "\n")
print(mat2, "\n")
print(mat3, "\n")
print(mat4, "\n")

[[10 15 18]
 [11 16 12]
 [14 18 15]] 

[[13 13 12]
 [11 10 12]
 [16 11 13]] 

[[19 19 11]
 [10 18 19]
 [17 16 17]] 

[[13 14 10]
 [16 12 17]
 [13 12 19]] 



In [70]:
step1 = np.hstack((mat1, mat3))
step1

array([[10, 15, 18, 19, 19, 11],
       [11, 16, 12, 10, 18, 19],
       [14, 18, 15, 17, 16, 17]])

In [71]:
step2 = np.hstack((mat2, mat4))
step2

array([[13, 13, 12, 13, 14, 10],
       [11, 10, 12, 16, 12, 17],
       [16, 11, 13, 13, 12, 19]])

In [66]:
final_step = np.vstack((step1, step2))
final_step

array([[10, 15, 18, 19, 19, 11],
       [11, 16, 12, 10, 18, 19],
       [14, 18, 15, 17, 16, 17],
       [13, 13, 12, 13, 14, 10],
       [11, 10, 12, 16, 12, 17],
       [16, 11, 13, 13, 12, 19]])

In [72]:
s1 = np.concatenate((mat1, mat3), axis = 1)
s1

array([[10, 15, 18, 19, 19, 11],
       [11, 16, 12, 10, 18, 19],
       [14, 18, 15, 17, 16, 17]])

In [73]:
s2 = np.concatenate((mat2, mat4), axis = 1)
s2

array([[13, 13, 12, 13, 14, 10],
       [11, 10, 12, 16, 12, 17],
       [16, 11, 13, 13, 12, 19]])

In [74]:
f_s = np.concatenate((s1, s2), axis = 0)
f_s

array([[10, 15, 18, 19, 19, 11],
       [11, 16, 12, 10, 18, 19],
       [14, 18, 15, 17, 16, 17],
       [13, 13, 12, 13, 14, 10],
       [11, 10, 12, 16, 12, 17],
       [16, 11, 13, 13, 12, 19]])

**Problem 11**

Generate a 100x100 dimensional array containing only integer 100 and flatten that array using reshape() function.

In [10]:
arr = np.full((100, 100), 100)
arr1 = arr.reshape(1,10000, order = "C")
arr1

array([[100, 100, 100, ..., 100, 100, 100]])

**Problem 12**

Generate a numpy array with shape (10,10) and integers in range \[0,100) in column-major order and perform transpose operation on it with numpy built-in method and with slicing (second approach may seem harder). 

In [15]:
h = np.arange(100)
h1 = h.reshape(10, 10, order = "F")
h1

array([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
       [ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91],
       [ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92],
       [ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93],
       [ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94],
       [ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95],
       [ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96],
       [ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97],
       [ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98],
       [ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99]])

In [16]:
h1.transpose()

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [17]:
h1_transpose = np.zeros((10, 10), dtype = int) #1st solution
for i in range(len(h1)):
    h1_transpose[i] = h1[:, i]

In [23]:
h1_transpose

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [3]:
np.arange(100).reshape((10,10), order="F")[[[i for i in range(10)] for j in range(10)],[[j for i in range(10)] for j in range(10)]] #2nd solution

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

**Problem 13**

Create a diagonal matrix with integers in range [1,10] on the diagonal. Extract the diagonal elements using slicing.

In [42]:
f = np.diag([1,2,3,4,5,6,7,8,9,10])
f

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10]])

In [41]:
l = f[f != 0]  # first solution
print(l)

[ 1  2  3  4  5  6  7  8  9 10]


In [91]:
for i,j in enumerate(f):  # second solution
    for k,l in enumerate(f):
        if i == k:
            print(f[i, k])


1
2
3
4
5
6
7
8
9
10


**Problem 14**

Create a 4x4 dimensional array where each row corresponds to integers from [1,4] in decreasing order and sort it rowwise. Now repeat the same operation using argsort and slicing.

In [1]:
d = np.array([[4,3,2,1]]*4)
d

array([[4, 3, 2, 1],
       [4, 3, 2, 1],
       [4, 3, 2, 1],
       [4, 3, 2, 1]])

In [2]:
d.sort(axis = 0) #Nothing will happen as the array is already sorted rowwise
d

array([[4, 3, 2, 1],
       [4, 3, 2, 1],
       [4, 3, 2, 1],
       [4, 3, 2, 1]])

In [5]:
d = np.array([[4,3,2,1]]*4)
print(d[d.argsort()[:,::-1],d.argsort()[:,::-1]])

[[4 3 2 1]
 [4 3 2 1]
 [4 3 2 1]
 [4 3 2 1]]


In [6]:
d=np.array([[4,3,2,1]]*4)
d[::-1,:]

array([[4, 3, 2, 1],
       [4, 3, 2, 1],
       [4, 3, 2, 1],
       [4, 3, 2, 1]])

***Problem 15***
<br> 5 students' test scores are stored in the 2-d array "student_scores". Each row stores the corresponding test's scores. <br>
Calculate the mean of grades of each student (columns) and the median of grades per test (rows)?

In [6]:
student_scores = np.array([[92, 94, 88, 91, 87],
                           [79, 100, 86, 93, 91],
                           [87, 85, 72, 90, 92]])

In [11]:
mean_grades = np.mean(student_scores, axis=0)
print(mean_grades)

[86.         93.         82.         91.33333333 90.        ]


In [13]:
median_grades = np.median(student_scores, axis = 1)
print(median_grades)

[91. 91. 87.]


**Problem 16**<br>
Create a logical statement that selects elements in "porridge" array that are less than 60, and saves them in a new array called "cold".<br>
Create a logical statement that finds all elements that are higher than 80 and saves them in an array named "hot".

In [14]:
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

In [17]:
cold = porridge[porridge < 60]
cold

array([50, 56, 51])

In [18]:
hot = porridge[porridge > 80]
hot

array([90, 85, 98])

# END